# Generated by Django 4.2.19 on 2025-02-23 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['week_num', '-sort_order']},
        ),
        migrations.AddField(
            model_name='task',
            name='week_num',
            field=models.CharField(default=514, max_length=3, verbose_name='Week'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='course_code',
            field=models.CharField(max_length=5, verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='task',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='Sort'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user_id',
            field=models.CharField(max_length=5, verbose_name='User'),
        ),
    ]
