# Generated by Django 4.2.19 on 2025-02-24 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_alter_task_options_task_week_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='week_num',
            field=models.IntegerField(verbose_name='Week'),
        ),
    ]
