# Generated by Django 4.2.19 on 2025-02-24 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_alter_task_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
    ]
