# Generated by Django 4.2.19 on 2025-02-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0005_remove_task_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['course_code', '-sort_order']},
        ),
        migrations.RemoveField(
            model_name='task',
            name='week_num',
        ),
        migrations.AlterField(
            model_name='task',
            name='course_code',
            field=models.IntegerField(verbose_name='Course'),
        ),
    ]
