# Generated by Django 4.2.19 on 2025-02-24 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0006_alter_task_options_remove_task_week_num_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['course_id', '-sort_order']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='course_code',
            new_name='course_id',
        ),
    ]
