# Generated by Django 4.2.19 on 2025-02-24 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0007_alter_task_options_rename_course_code_task_course_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.IntegerField(max_length=2, primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=5, unique=True, verbose_name='Course Code')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
            ],
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['course__course_code', 'user_id', 'sort_order']},
        ),
        migrations.RemoveField(
            model_name='task',
            name='course_id',
        ),
        migrations.AddField(
            model_name='task',
            name='course',
            field=models.ForeignKey(default=41, on_delete=django.db.models.deletion.CASCADE, to='progress.course'),
            preserve_default=False,
        ),
    ]
