# Generated by Django 4.2.19 on 2025-02-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0009_alter_course_course_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['course__short_code', 'user_id', 'sort_order']},
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_code',
        ),
        migrations.AddField(
            model_name='course',
            name='short_code',
            field=models.CharField(default=42, max_length=5, unique=True, verbose_name='Short Code'),
            preserve_default=False,
        ),
    ]
