# Generated by Django 4.2.19 on 2025-02-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0010_alter_task_options_remove_course_course_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='short_code',
            field=models.CharField(max_length=5, verbose_name='Short Code'),
        ),
    ]
