# Generated by Django 4.2.19 on 2025-02-24 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0011_alter_course_short_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['user_id', 'sort_order']},
        ),
        migrations.RemoveField(
            model_name='course',
            name='short_code',
        ),
    ]
