# Generated by Django 4.2.19 on 2025-02-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0012_alter_task_options_remove_course_short_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(default=42, max_length=5, verbose_name='Short Code'),
            preserve_default=False,
        ),
    ]
