# Generated by Django 4.2.19 on 2025-02-24 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0013_course_course_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_code',
            new_name='short_code',
        ),
    ]
