# Generated by Django 4.2.19 on 2025-02-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0014_rename_course_code_course_short_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='day',
            field=models.IntegerField(default=0),
        ),
    ]
