# Generated by Django 4.2.19 on 2025-02-24 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0015_task_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['course_id', 'user_id', 'day', 'sort_order']},
        ),
    ]
